Repository NVIDIA/nvidia-container-toolkit, pull requests merged in 2025-05, with the labels that each got.

#1065 Skip nil discoverers in merge
  internal/discover/list.go
Labels: must-backport

#1046 Fix resolution of libs in LDCache on ARM
  internal/ldcache/ldcache.go
Labels: must-backport

#1069 [no-relnote] Skip nil discoverers in merge
  internal/discover/list.go
Labels: backport

#1068 Fix resolution of libs in LDCache on ARM
  internal/ldcache/ldcache.go
Labels: backport

#1078 Fix mode detection on Thor-based systems
  go.mod
  go.sum
  internal/info/auto_test.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/nvlib/device/mig_device.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/nvlib/info/api.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/nvlib/info/property-extractor.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/nvlib/info/property-extractor_mock.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/nvlib/info/resolver.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/nvpci/mmio/mmio.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/nvpci/mmio/mock.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/nvpci/mock.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/pciids/default_pci.ids
  vendor/modules.txt
Labels: must-backport

#1079 Fix mode detection on Thor-based systems
  go.mod
  go.sum
  internal/info/auto_test.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/nvlib/device/device.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/nvlib/device/mig_device.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/nvlib/info/api.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/nvlib/info/property-extractor.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/nvlib/info/property-extractor_mock.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/nvlib/info/resolver.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/nvpci/mmio/mmio.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/nvpci/mmio/mock.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/nvpci/mock.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/nvpci/nvpci.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/nvpci/resources.go
  vendor/github.com/NVIDIA/go-nvlib/pkg/pciids/default_pci.ids
  vendor/github.com/NVIDIA/go-nvlib/pkg/pciids/pciids.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_custom.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_default.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_fail.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: backport

#1055 Add nvidia-container-cli.compat-mode config option
  cmd/nvidia-container-runtime-hook/hook_config.go
  cmd/nvidia-container-runtime-hook/main.go
  cmd/nvidia-ctk-installer/main_test.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/runtime.go
  internal/config/toml_test.go
  internal/modifier/gated.go
Labels: must-backport

#1102 Edit discover.mounts to have a deterministic output
  internal/discover/mounts.go
  internal/discover/mounts_test.go
Labels: must-backport

#1104 [release-1.17] Edit discover.mounts to have a deterministic output
  internal/discover/mounts.go
  internal/discover/mounts_test.go
Labels: backport

#1117 Fix unit tests
  internal/modifier/discover_test.go
Labels: maintenance
