Repository NVIDIA/nvidia-container-toolkit, pull requests merged in 2025-07, with the labels that each got.

#1168 Fix leaking of tmpfs mount in CDI mode
  cmd/nvidia-cdi-hook/disable-device-node-modification/params_linux.go
  tests/e2e/nvidia-container-toolkit_test.go
Labels: bug

#1172 [no-relnote] fix(systemd): Support alternative nvidia-smi path in refresh service
  deployments/systemd/nvidia-cdi-refresh.service
Labels: bug

#1175 Use securejoin to resolve /proc
  internal/ldconfig/ldconfig_linux.go
Labels: must-backport

#1176 Use securejoin to resolve /proc
  cmd/nvidia-cdi-hook/update-ldcache/ldconfig_linux.go
Labels: backport
