Repository NVIDIA/nvidia-container-toolkit, pull requests merged in 2025-02, with the labels that each got.

#898 [no-relnote] switch to the newer qemu artifacts image
  .github/workflows/image.yaml
Labels: backport

#913 [no-relnote] Run e2e tests as reusable workflow
  .github/workflows/e2e.yaml
  .github/workflows/image.yaml
  deployments/container/Makefile
  deployments/container/multi-arch.mk
  deployments/container/native-only.mk
Labels: testing

#894 Allow cdi mode to work with --gpus flag
  internal/modifier/csv.go
  internal/modifier/csv_test.go
  internal/modifier/hook_remover.go
  internal/runtime/runtime_factory.go
  internal/runtime/runtime_factory_test.go
  tests/e2e/nvidia-container-toolkit_test.go
Labels: must-backport

#917 Remove nvidia container runtime hook in cdi mode
  internal/modifier/csv.go
  internal/modifier/csv_test.go
  internal/modifier/hook_remover.go
  internal/runtime/runtime_factory.go
  internal/runtime/runtime_factory_test.go
Labels: backport

#935 Disable nvsandboxutils in nvcdi API
  pkg/nvcdi/lib.go
Labels: must-backport

#906 Add CUDA forward compatibility hook
  cmd/nvidia-cdi-hook/commands/commands.go
  cmd/nvidia-cdi-hook/cudacompat/container-root.go
  cmd/nvidia-cdi-hook/cudacompat/cudacompat.go
  cmd/nvidia-cdi-hook/cudacompat/cudacompat_test.go
  cmd/nvidia-ctk-installer/container/toolkit/toolkit_test.go
  cmd/nvidia-ctk/cdi/generate/generate.go
  cmd/nvidia-ctk/cdi/generate/generate_test.go
  internal/config/features.go
  internal/discover/compat_libs.go
  internal/modifier/gated.go
  internal/runtime/runtime_factory.go
  pkg/nvcdi/driver-nvml.go
  tests/e2e/nvidia-container-toolkit_test.go
  vendor/github.com/NVIDIA/go-nvml/pkg/nvml/mock/dgxa100/dgxa100.go
  vendor/github.com/NVIDIA/go-nvml/pkg/nvml/mock/dgxa100/mig-profile.go
  vendor/modules.txt
Labels: must-backport

#941 Use memfd when running ldconfig
  cmd/nvidia-cdi-hook/update-ldcache/container-root.go
  cmd/nvidia-cdi-hook/update-ldcache/safe-exec_linux.go
  cmd/nvidia-cdi-hook/update-ldcache/safe-exec_other.go
  cmd/nvidia-cdi-hook/update-ldcache/update-ldcache.go
  go.mod
  go.sum
  vendor/github.com/cyphar/filepath-securejoin/CHANGELOG.md
  vendor/github.com/cyphar/filepath-securejoin/LICENSE
  vendor/github.com/cyphar/filepath-securejoin/README.md
  vendor/github.com/cyphar/filepath-securejoin/VERSION
  vendor/github.com/cyphar/filepath-securejoin/doc.go
  vendor/github.com/cyphar/filepath-securejoin/gocompat_errors_go120.go
  vendor/github.com/cyphar/filepath-securejoin/gocompat_errors_unsupported.go
  vendor/github.com/cyphar/filepath-securejoin/gocompat_generics_go121.go
  vendor/github.com/cyphar/filepath-securejoin/gocompat_generics_unsupported.go
  vendor/github.com/cyphar/filepath-securejoin/join.go
  vendor/github.com/cyphar/filepath-securejoin/lookup_linux.go
  vendor/github.com/cyphar/filepath-securejoin/mkdir_linux.go
  vendor/github.com/cyphar/filepath-securejoin/open_linux.go
  vendor/github.com/cyphar/filepath-securejoin/openat2_linux.go
  vendor/github.com/cyphar/filepath-securejoin/openat_linux.go
  vendor/github.com/cyphar/filepath-securejoin/procfs_linux.go
  vendor/github.com/cyphar/filepath-securejoin/vfs.go
  vendor/github.com/opencontainers/runc/LICENSE
  vendor/github.com/opencontainers/runc/NOTICE
  vendor/github.com/opencontainers/runc/libcontainer/dmz/cloned_binary_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/dmz/overlayfs_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/system/linux.go
  vendor/github.com/opencontainers/runc/libcontainer/system/proc.go
  vendor/github.com/opencontainers/runc/libcontainer/system/rlimit_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/system/rlimit_linux_go122.go
  vendor/github.com/opencontainers/runc/libcontainer/utils/cmsg.go
  vendor/github.com/opencontainers/runc/libcontainer/utils/utils.go
  vendor/github.com/opencontainers/runc/libcontainer/utils/utils_unix.go
  vendor/modules.txt
Labels: must-backport

#948 Add CUDA forward compatibility hook
  cmd/nvidia-cdi-hook/commands/commands.go
  cmd/nvidia-cdi-hook/cudacompat/container-root.go
  cmd/nvidia-cdi-hook/cudacompat/cudacompat.go
  cmd/nvidia-cdi-hook/cudacompat/cudacompat_test.go
  internal/config/features.go
  internal/discover/compat_libs.go
  internal/modifier/gated.go
  internal/runtime/runtime_factory.go
  pkg/nvcdi/driver-nvml.go
Labels: backport

#945 Disable nvsandboxutils in nvcdi API
  pkg/nvcdi/lib.go
Labels: backport

#943 Add ignore-imex-channel-requests feature flag
  cmd/nvidia-container-runtime-hook/container_config.go
  internal/config/features.go
Labels: must-backport
